service: aws-rest-api

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-2 

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: get
